<<<<<<< HEAD
language: java
jdk:
    - openjdk8
cache:
    directories:
        - "$HOME/.cache"
jobs:
    - stage: deploy
      name: 'Deploy To Dev Environment'
      script:
       - mvn clean verify
       - mvn clean install
       - cp .travis.settings.xml $HOME/.m2/settings.xml
       - mvn deploy -DmuleDeploy -Dserver=$server -Denvironment=$environment -Dworkers=$workers -DworkerType=$workerType -DmuleVersion=$muleVersion -DappName=$appName
=======
language: java
jdk:
    - openjdk8
cache:
    directories:
        - $HOME/.cache
jobs:
    - stage: deploy
      name: 'Deploy To Dev Environment'
      script:
       - mvn clean install
       - cp .travis.settings.xml $HOME/.m2/settings.xml
       - mvn dependency:purge-local-repository -DmanualInclude="org.mule.tools.maven:mule-app-maven-plugin:1.7"
       - mvn deploy -DmuleDeploy -Dserver=$server -Denvironment=$environment -Dworkers=$workers -DworkerType=$workerType -DmuleVersion=$muleVersion -DappName=$appName
>>>>>>> af8ad523c51c1bcca196fc69cc98a943555bbb06
      if: branch = dev